---
- name: Configure Bitwarden
  import_tasks: bitwarden.yml
  tags: bitwarden

- name: Install and apply dotfiles with Chezmoi
  import_tasks: dotfiles.yml
  tags: dotfiles

- name: Install Hyprland desktop
  import_tasks: hyprland.yml
  tags: hyprland

- name: Install Graphical Frameworks
  import_tasks: graph-frameworks.yml
  tags: graph-frameworks

- name: Install SDDM
  import_tasks: sddm.yml
  tags: sddm
