---
- name: Install SDDM
  community.general.pacman:
    name:
    - sddm
    state: present
  become: true

- name: Start SDDM service
  ansible.builtin.systemd_service:
    name: sddm
    enabled: true
