---
- name: Set Orchis variables
  set_fact:
    repo_url: "https://github.com/tristanmsct/orchis-theme-git.git"
    repo_dest: "{{ user_home }}/.local/share/aur/orchis-theme-git"
    check_path: "/usr/share/themes/Orchis-Blue-Dark-Compact"

- name: Check if Orchis theme is already installed
  stat:
    path: "{{ check_path }}"
  register: orchis_installed

- name: Install Orchis Theme
  block:
    - name: Clone Orchis repo
      git:
        repo: "{{ repo_url }}"
        dest: "{{ repo_dest }}"
        update: yes

    - name: Run makepkg
      command:
        cmd: makepkg -si --noconfirm
        chdir: "{{ repo_dest }}"
      become: false

    - name: Cleanup makepkg build artifacts
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - "{{ repo_dest }}/src"
        - "{{ repo_dest }}/pkg"

    - name: Cleanup makepkg package files
      file:
        path: "{{ item }}"
        state: absent
      loop: "{{ lookup('fileglob', repo_dest + '/*.pkg.tar.zst', repo_dest + '/*.src.tar.gz', wantlist=True) }}"

  when: not orchis_installed.stat.exists
