---
- name: Set Tela Circle variables
  set_fact:
    repo_url: "https://github.com/tristanmsct/tela-circle-icon-theme-git.git"
    repo_dest: "{{ user_home }}/.local/share/aur/tela-circle-icon-theme-git"
    check_path: "/usr/share/icons/Tela-circle-blue"

- name: Check if Tela Circle theme is already installed
  stat:
    path: "{{ check_path }}"
  register: tela_circle_installed

- name: Install Tela Circle Theme
  block:
    - name: Clone Tela Circle repo
      git:
        repo: "{{ repo_url }}"
        dest: "{{ repo_dest }}"
        update: yes

    - name: Run makepkg
      command:
        cmd: makepkg -si --noconfirm
        chdir: "{{ repo_dest }}"
      become: false

    - name: Cleanup makepkg build artifacts
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - "{{ repo_dest }}/src"
        - "{{ repo_dest }}/pkg"

    - name: Cleanup makepkg package files
      file:
        path: "{{ item }}"
        state: absent
      loop: "{{ lookup('fileglob', repo_dest + '/*.pkg.tar.zst', repo_dest + '/*.src.tar.gz', wantlist=True) }}"

  when: not tela_circle_installed.stat.exists
