---
- name: Install audio dependencies
  pacman:
    name:
      - pipewire
      - pipewire-pulse
      - pipewire-alsa
      - pipewire-jack
      - sof-firmware
      - alsa-utils
    state: present
    update_cache: yes
  become: true

- name: Start Apache service
  ansible.builtin.service:
    name: pipewire
    state: started
    scope: user

- name: Start Apache service
  ansible.builtin.service:
    name: wireplumber
    state: started
    scope: user
