---
- name: Install NWG Apps
  community.general.pacman:
    name:
      - nwg-drawer
      - nwg-look  # This is a GTK4 theme manager
      - nwg-menu
    state: present
    update_cache: yes
  become: true
