---
# handlers/main.yml
- name: daemon reload
  ansible.builtin.systemd:
    daemon_reload: yes
  become: yes

- name: restart networkmanager
  ansible.builtin.service:
    name: NetworkManager
    state: restarted
  become: yes

- name: restart auditd
  ansible.builtin.service:
    name: auditd
    state: restarted
  become: yes

- name: restart bluetooth
  ansible.builtin.service:
    name: bluetooth
    state: restarted
  become: yes
