---
- name: Create AUR builder user
  ansible.builtin.user:
    name: aur_builder
    create_home: yes
    home: /var/cache/aur_builder
    shell: /bin/bash        # needs real shell for makepkg
    password: '!'
    groups: []
  become: true

- name: Allow aur_builder passwordless pacman
  ansible.builtin.copy:
    dest: /etc/sudoers.d/11-aur
    content: |
      aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman
    mode: '0440'
    validate: 'visudo -cf %s'
  become: true

- name: Check yay installed
  ansible.builtin.stat:
    path: /usr/bin/yay
  register: yay_binary

- name: Install yay
  block:
    - name: Clone yay from github
      git:
        repo: https://aur.archlinux.org/yay.git
        dest: /tmp/yay
        version: master
        update: yes
      become: false

    - name: Build yay package
      command: makepkg --noconfirm -s
      args:
        chdir: /tmp/yay
        creates: /tmp/yay/yay-*.pkg.tar.zst
      become: false

    - name: Install yay package
      shell: pacman -U --noconfirm yay-*.pkg.tar.zst
      args:
        chdir: /tmp/yay
      become: true
  when: not yay_binary.stat.exists
