---
- name: Create AUR user
  user:
    name: aur_builder
    create_home: yes
    home: /var/cache/aur_builder
    shell: /usr/bin/nologin
    password: '!'  # locked, no password login
    groups: []     # no wheel or other groups
  become: true
  tags:
    - aur-user

- name: Allow passwordless Pacman for AUR user
  template:
    src: sudo_aur.j2
    dest: /etc/sudoers.d/11-aur
    mode: 0644
    validate: 'visudo -cf %s'
  become: true
  tags:
    - aur-user
