---
- name: Install base packages
  pacman:
    name:
      - git
      - kitty
      - nautilus
    state: present
    update_cache: yes
  become: true

- name: Configure pacman
  import_tasks: pacman.yml
  tags: pacman

- name: Setup AUR helper
  import_tasks: aur.yml
  tags: aur

- name: Setup AUR helper user
  import_tasks: aur_user.yml
  tags: aur-user


