---
- name: Modify makepkg configuration
  lineinfile:
    path: /etc/makepkg.conf
    regexp: '^#?\s*{{ item.key }}'
    line: "{{ item.key }}={{ item.value }}"
    backrefs: yes
  with_items:
    - key: MAKEFLAGS
      value: '"-j$(nproc)"'
    - key: COMPRESSXZ
      value: (xz -c -z - --threads=0)
  become: true

- name: Enable pacman options
  lineinfile:
    path: /etc/pacman.conf
    regexp: '^#?\s*{{ item }}'
    line: "{{ item }}"
    backrefs: yes
  with_items:
    - Color
    - CheckSpace
  become: true

- name: Enable pacman parrallel downloads
  lineinfile:
    path: /etc/pacman.conf
    regexp: '^#?\s*{{ item.key }}\s*=?.*'
    line: "{{ item.key }} = {{ item.value }}"
    backrefs: yes
  with_items:
    - key: ParallelDownloads
      value: "{{ [ansible_facts['processor_vcpus'], 8] | min }}"
  become: true

- name: Enable pacman ILoveCandy
  lineinfile:
    path: /etc/pacman.conf
    insertafter: '^Color$'
    line: "ILoveCandy"
    state: present
  become: true

# --- reflector -------------------------------------------------------------------------
- name: Install reflector
  community.general.pacman:
    name:
      - reflector
    state: present
    update_cache: yes
  become: true

- name: Start reflector
  ansible.builtin.systemd_service:
    name: reflector.timer
    enabled: yes
    state: started

# --- Pacman hook Grub silencer ---------------------------------------------------------
- name: Ensure pacman hooks dir exists
  file:
    path: /etc/pacman.d/hooks
    state: directory
    mode: '0755'

- name: Deploy pacman hook
  template:
    src: grub-quiet.hook.j2
    dest: /etc/pacman.d/hooks/grub-quiet.hook
    mode: '0644'
  become: true
