---
- name: Install Kitty terminal emulator
  community.general.pacman:
    name:
      - kitty
    state: present
    update_cache: yes
  become: true

- name: Install some shell tools
  community.general.pacman:
    name:
      - kitty-shell-integration
      - bash-completion
      - zsh-completion
    state: present
    update_cache: yes
  become: true

- name: Install oh-my-zsh
  kewlfft.aur.aur:
    name:
      - oh-my-zsh-git
  become: yes
  become_user: "{{ aur.user }}"

- name: Install other zsh plugins
  community.general.pacman:
    name:
      - zsh-syntax-highlighting
      - zsh-autosuggestions
    state: present
    update_cache: yes
  become: true

- name: Install other zsh plugins from the AUR
  kewlfft.aur.aur:
    name:
      - zsh-fast-syntax-highlighting
  become: yes
  become_user: "{{ aur.user }}"

- name: Install zsh themes
  kewlfft.aur.aur:
    name:
      - zsh-theme-powerlevel10k-git
      - ttf-meslo-nerd-font-powerlevel10k
      - oh-my-posh
  become: yes
  become_user: "{{ aur.user }}"

- name: Configure ZDOTDIR in /etc/zsh/zshenv
  ansible.builtin.copy:
    dest: /etc/zsh/zshenv
    content: |
      if [[ -d "$HOME/.config/shell/zsh" ]]; then
        export ZDOTDIR="$HOME/.config/shell/zsh"
      fi
    owner: root
    group: root
    mode: '0644'
  become: true

- name: Set zsh as default shell
  ansible.builtin.user:
    name: "{{ ansible_facts['user_id'] }}"
    shell: /bin/zsh
  become: true
