---
- name: Install CLI tools
  community.general.pacman:
    name:
      - vim
      - neovim
      - fzf
      - zoxide
      - fd
      - eza
      - bat
      - git-delta
      - ripgrep
      - ncdu
      - glow
      - tldr
      - thefuck
      - btop
    state: present
    update_cache: yes
  become: true

- name: Install trash-cli
  community.general.pacman:
    name:
      - trash-cli
    state: present
    update_cache: yes
  become: true

- name: Start trash-cli service
  ansible.builtin.systemd_service:
    name: empty-trash.timer
    enabled: true
    scope: user

- name: Install other usefull cli tools
  community.general.pacman:
    name:
      - unzip
      - fastfetch
      - ddcutils
      - figlet
      - gum
      - imagemagick
      - jq
    state: present
    update_cache: yes
  become: true
