---
- name: Include UFW vars
  ansible.builtin.include_vars:
    file: ufw.yml  # loads from roles/cli/vars/

- name: Install UFW
  community.general.pacman:
    name: ufw
    state: present
  become: true

- name: Enable and start UFW service
  ansible.builtin.systemd:
    name: ufw
    enabled: true
    state: started
  become: true

- name: Set default incoming policy to deny
  community.general.ufw:
    default: deny
    direction: incoming
  become: true

- name: Set default outgoing policy to allow
  community.general.ufw:
    default: allow
    direction: outgoing
  become: true

- name: Enable UFW
  community.general.ufw:
    state: enabled
  become: true
